### ISSUE TITLE
What is the reason for creating graphql-crunch when graphql-deduplicator is available?

### ISSUE THREAD

**Issue by gajus** [banterfm/graphql-crunch#15]
This package seems to mimic the behaviour [graphql-deduplicator](https://github.com/gajus/graphql-deduplicator), which has been available for a long-time before `graphql-crunch`. What is your motivation for maintaining your own implementation and would you not rather contribute to the former library?

**Comment by jamesreggio** [comment]
I explained our reasoning here: https://github.com/prisma/graphql-yoga/issues/303#issuecomment-386383356

It boils down to a difference in design objective: we sought to be totally lossless in our format, so as to minimize potential for unexpected bugs or surprises, whereas your format leans upon conventions around GraphQL payload normalization to function.

Also worth noting: the name `graphql-crunch` is a misnomer — this works for any JSON payload. We chose to call it `graphql-crunch` because it's easier to market something when it sounds tailored to a specific problem domain.
