### ISSUE TITLE
Explanation of the v2 `encode` function

### ISSUE THREAD

**Issue by mainrs** [banterfm/graphql-crunch#37]
Hey!
I have most of my (GraphQL) servers written in Rust and wanted to port the algorithm used here to make it compatible with the JS world.

However, I do not really understand the need of the `encode` function when it comes down to numbers. Why are they multiplied by 2 (and sometimes incremented by 1)?
Additionally, wouldn't multiplying the value by 2 decrease the available number space to half its normal size? Meaning that servers can't use the whole number range?

**Comment by stevekrenzel** [comment]
We encode integers because they double as references.

If you have the JSON:

```javascript
{
  a: [7]
  b: [7]
} 
```

We could encode it as something like:

```javascript
[
7,                // <-- this is a value
[0],              // <-- this is an array that references 7
{a: 1, b: 1},     // <-- this is an object where both keys reference the array
]
```

The problem is that this would be ambiguous with:

```javascript
{
  a: [7],
  b: 1,
}
```

This would also get crunched as: 

```javascript
[
7,
[0],
{a: 1, b: 1},      // <-- this is an object that references the array, but also just has an int of value `1`
]
```

So we need some quick, efficient, and compact way to differentiate references from all other types in the JSON spec.

Fortunately, numbers in JSON are unbounded. And in javascript, the effective upper limit for an int is `2^53`. So we do take a hit and reserve a bit's worth of integers to be used by references.

Alternatives could have been something like:
- Start references at 2^52
- Encode references as strings with a prefixed sequence that normal strings would escape if they happen to include them.

But they all wind up taking a lot more space
